### ISSUE TITLE
Project is set to read-only when opened in GameMaker

### ISSUE THREAD

**Issue by ryboy111** [QuantumV2/BeachAndForestDecomp#1]
![image_2023-12-08_140448450](https://github.com/QuantumV2/BeachAndForestDecomp/assets/81989582/cc2ace37-ad2a-4e52-bc47-61b010530e5b)

**Comment by ryboy111** [comment]
![image](https://github.com/QuantumV2/BeachAndForestDecomp/assets/81989582/e68f50b5-8261-4b54-a196-51856b4c0e07)

**Comment by QuantumV2** [comment]
you should use latest IDE version with runtime 2023.6.0.139.
